### ISSUE TITLE
Follow other participants most recent Mood Event

### ISSUE THREAD

**Issue by rkluzinski** [CMPUT301F19T34/MOODeration#14]
**US 05.01.01**
**As a** participant, **I want** to ask another participant to follow their most recent mood event **so that** I can keep track of my friends most recent mood.

**Comment by rkluzinski** [comment]
Most recent Mood Event is updated as the followed user adds a new Mood Event. https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1232397

**Comment by mdepp** [comment]
Going to first make a fragment to view a user profile, then add a 'follow' button to it

**Comment by rkluzinski** [comment]
User A is able to follow User B without user B following user A. Removing followers is considered a "could do" (although I think we should consider it as should do). https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1254413
