### ISSUE TITLE
Mood event form fields might not be persistant

### ISSUE THREAD

**Issue by mdepp** [CMPUT301F19T34/MOODeration#29]
The values for the add mood event form are not stored in a viewmodel. If this were an activity, I know that doing this would mean the values would be erased every time the activity is re-created (e.g. at screen rotation). Is this also an issue for the fragments approach?

**Comment by rkluzinski** [comment]
Yes, I believe this will be an issue with Fragments as well. Good catch.

**Comment by rkluzinski** [comment]
Fixed in #82
